// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sjpynjeqpgdoakjimthm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNqcHluamVxcGdkb2FramltdGhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzODYyODksImV4cCI6MjA2NTk2MjI4OX0.e2dD9R8zyrmnSAHC-Xi04nDdyKvCmj2I3PpQndWqXYY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);